run:
  allow-parallel-runners: true
issues:
  exclude-dirs:
    - ^observability/tracing/http/semconvutil$ # нельзя модифицировать
  exclude-rules:
    - path: lb
      linters: 
        - gosec # нету необходимости менять math/rand на crypto/rand
    - path: metrics
      linters: 
        - promlinter # свой стиль наименования метрик
linters:
  enable-all: true
  disable:
    - goimports #у нас собственные правила форматирования импортов
    - wsl #расставление пробелов очень индивидуально
    - varnamelen #очень индивидуально (db)
    - exhaustruct #не имеет смысла
    - contextcheck #не имеет смысла
    - gci #у нас собственные правила форматирования импортов
    - gofumpt #у нас собственные правила форматирования импортов
    - nolintlint #Goland все равно форматирует с отступом
    - nlreturn #не всегда имеет смысл
    - godot #не актуально для свагера
    - godox #не позволяет оставлять todo
    - depguard #не всегда имеет смысл
    - dupword #не имеет смысла
    - tagalign #не всегда имеет смысл
    - musttag #у нас собственные правило: не используем теги, если работаем с пакетом isp-kit/json и с внутренними структурами(между нашими сервисами), при этом теги обязательный для всех внених для нас структур
    - perfsprint #мнимая производительность в угоду читаемости
    - tenv #устарел
    - containedctx
    - wrapcheck #не имеет смысла для модулей обёрток,в либе очень много таких модулей
linters-settings:
  funlen:
    lines: 80
  lll:
    line-length: 150
  cyclop:
    max-complexity: 15 #по умолчанию 10 мало
  revive:
    rules:
      - name: var-naming #отключаем Id -> ID
        disabled: true
  stylecheck:
    checks: #отключаем Id -> ID
      - "-ST1000"
      - "-ST1016"
      - "-ST1020"
      - "-ST1021"
      - "-ST1022"
  testifylint:
    disable:
      - compares
