version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - contextcheck # не имеет смысла
    - depguard # не всегда имеет смысл
    - dupword # не имеет смысла
    - exhaustruct # не имеет смысла
    - godot # не актуально для swagger
    - godox # не позволяет оставлять todo
    - musttag # у нас собственное правило: не используем теги, если работаем с пакетом isp-kit/json и с внутренними структурами(между нашими сервисами), при этом теги обязательный для всех внешних для нас структур
    - nlreturn # не всегда имеет смысл
    - nolintlint # Goland все равно форматирует с отступом
    - perfsprint # мнимая производительность в угоду читаемости
    - tagalign # не всегда имеет смысл
    - varnamelen # очень индивидуально (db)
    - wsl # расставление пробелов очень индивидуально
    - wrapcheck # не имеет смысла для модулей обёрток, в либе очень много таких модулей
  settings:
    cyclop:
      max-complexity: 15 # по умолчанию 10 мало
    funlen:
      lines: 80
    lll:
      line-length: 150
    revive:
      rules:
        - name: var-naming # отключаем Id -> ID
          disabled: true
    staticcheck:
      checks: # отключаем Id -> ID
        - -ST1000
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
    testifylint:
      disable:
        - compares
        - equal-values
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: lb
        linters:
          - gosec # нету необходимости менять math/rand на crypto/rand
      - path: metrics
        linters:
          - promlinter # свой стиль наименования метрик
    paths:
      - third_party$
      - builtin$
      - examples$
      - observability/tracing/http/semconvutil  # нельзя модифицировать
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - observability/tracing/http/semconvutil  # нельзя модифицировать
